version: "3.8"

services:
  yolo-ecommerce-client:
    image: kenanricky/yolo-ecommerce-client:v1.0.0
    build: ./client
    container_name: yolo-client
    ports:
      - "3000:3000"
    depends_on:
      - yolo-ecommerce-backend
    networks:
      - yolo-network

  yolo-ecommerce-backend:
    image: kenanricky/yolo-ecommerce-backend:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yolo-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://kaburaricky:ricky2025@mongo:27017/RickyCluster?authSource=admin
    networks:
      - yolo-network

  mongo:
    image: mongo
    container_name: yolo-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kaburaricky
      MONGO_INITDB_ROOT_PASSWORD: ricky2025
      MONGO_INITDB_DATABASE: RickyCluster
    volumes:
      - yolo-data:/data/db
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

volumes:
  yolo-data:
