version: "3.8"

services:
  # MongoDB Database Service
  app-mongo:
    image: mongo:7.0
    container_name: app-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kaburaricky
      MONGO_INITDB_ROOT_PASSWORD: ricky2025
      MONGO_INITDB_DATABASE: RickyCluster
    networks:
      - ecommerce-network
    volumes:
      - project-data:/data/db

  # Backend  Service
  ricky-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend-runner
    image: kenanricky/ricky-ecommerce-backend:v1.0.0
    container_name: ricky-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb+srv://kaburaricky:ricky2025@rickycluster.yknl9gf.mongodb.net/?retryWrites=true&w=majority&docker-compose-project=RickyCluster
    depends_on:
      - app-mongo
    networks:
      - ecommerce-network
    volumes:
      - project-data:/backend

  # Frontend Application Service
  ricky-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kenanricky/ricky-ecommerce-frontend:v1.0.0
    container_name: ricky-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      NODE_ENV: production
    depends_on:
      - ricky-backend
    networks:
      - ecommerce-network
    volumes:
      - project-data:/client

# Network Configuration
networks:
  ecommerce-network:
    driver: bridge

# Volume Configuration
volumes:
  project-data:

