---
- name: Pull the image
  docker_container:
    name: frontend_container
    image: kenanricky/yolo-ecommerce-client:v1.0.0
    ports:
       - "3000:3000"
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: yolo-network
  tags:
    - database
    - backend
