---
- name: Pull the image
  docker_image:
    name: kenanricky/yolo-ecommerce-backend:v1.0.0
    source: pull
 

- name: Create Node.js Backend Container
  docker_container:
    name: yolo-backend
    image: kenanricky/yolo-ecommerce-backend:v1.0.0
    networks:
      - name: yolo-network
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes


- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Wait for Docker to be ready
  shell: docker info
  register: docker_ready
  retries: 5
  delay: 3
  until: docker_ready.rc == 0

- name: Pull the image
  community.docker.docker_image:
    name: your-image-name
    source: pull
